### PR TITLE
Session table 2

### PR DESCRIPTION
**Pull request by kenirwin**
* creates page http://localhost:4000/session-table; not currently linked anywhere
* adds ` _partials/_session-table.scss`
* adds a new section in `scripts.js`
* shows all sessions in tabular format, linking to session modals
* creates a posters-modal include
* textbox filters by all content (including abstract/description, which is not visible - e.g. search on "nemesis" which will find the one session that uses the word in its description) 
* dynamically creates pulldowns for session type and for presenter name
* this pulldown can be later extended to include other filter items such as "track" ("special collection", "administration", etc.) 
* there are bunch of extra "files changed" because of rebasing this commit a few times
* is a start on #65 

Problems to solve (possible new issues): 
* there's a bit of CSS screwiness inherited from `.slot` styles in the session grid (some oddity in borders) -- let's clean that up.
* need to show the session time somewhere -- let's discuss the best place to do it?
* where do we want to link this from? Do we add a "sessions" link to the main navigation, or link to it from the sessions grid page? I have a bit of a preferences for putting it in main nav but I'm open to other ideas. 
* It might ought to be named "sessions" instead of "session-table", or perhaps make the url path /sessions/ and still keep the files names session-table for clarity. The word "session" gets used a lot in the code as it is.
* eventually will need additional filters

### CODE REVIEW

**Comment by dzoladz** [comment]
> there's a bit of CSS screwiness inherited from .slot styles in the session grid (some oddity in borders) -- let's clean that up.

Can you point this out to me in a screenshot?

**Comment by kenirwin** [comment]
@dzoladz - here's the border weirdness. You'll see that the red arrows to a solid grey border running down the length of the right side. Meanwhile, on the left, the orange arrow in points to a grey border in the first cell, but the purple arrow shows where there are no left borders on the subsequent rows. 
Screen Shot 2020-06-29 at 8 56 31 AM

It's subtle, but I noticed it after a while.

The linking functionality in the session grid is attached to the ".slot" class, but so are some border ideas specific to the grid situation that don't apply as well here. I wasn't worried about rooting it out in the first pass at the table, but wanted to make sure we didn't lose track of it.

**Comment by kenirwin** [comment]
Fixed border issue

**Comment by kenirwin** [comment]
Thanks for the CSS upgrades @dzoladz!

I'm satisfied that this is ready to go (though we'll still need to figure out where to link it from.)

**Comment by dzoladz** [comment]
@kenirwin Thanks for fixing the border issue. Let me take another look either early this afternoon or this evening, when I get back from the dentist. If all checks out, I'll merge the changes into master and we send out a direct link to the live site to let everyone on the team take a look. I'll do this in an email and ask if there are any strong opinions on where we should place the link on the site.

**Comment by kenirwin** [comment]
@dzoladz - sounds good

**Pull request merged**
