### PR TITLE
implemented Q&A launch option

### LINKED ISSUE #26: Add 'Join Q&A' Button to Session Modals
Adding a button to launch a Zoom meeting Q&A from each session's modal in the conference schedule seems to be the easily way to communicate those Zoom links to conference attendees.

I'm open to other ideas and thoughts on how to be solve the problem of making it easy for conference attendees to join the keynote and Q&A Zoom meetings.

### PR DESCRIPTION
**Pull request by kenirwin**
* activated by presence of "question-time" and "question-link" data elements
* needs nicer CSS
* we may need to consider timezone handling
* fixes #26

### CODE REVIEW

**Comment by dzoladz** [comment]
I'll take a look at the CSS in just a bit.

**Comment by dzoladz** [comment]
@kenirwin added a commit to establish some styling for the qa-* row in the session modal. Do you think we need to vertically-align the 'View Presentation' link? Or, perhaps make it a button?

**Comment by kenirwin** [comment]
What's the difference between the "view presentation" link and the embedded video? I see that they have two separate data elements, but I don't know why. Depending on how we intend them to be used, it might make sense to make the presentation a button too -- maybe two different colors for the buttons.

**Comment by dzoladz** [comment]
I was thinking of 'View Presentation' as a resource link to provide speaker notes, handouts, slides, or other presentation materials outside of the presentation itself.

**Pull request merged**
